title: Networking & Communications Conference Deadlines
description: Countdowns to top Networking & Communications conference deadlines.
author: TBD

domain: "netcom-deadlines.github.io"
# baseurl: "netcom-deadlines.github.io"
# Use this baseurl for local testing with `jekyll serve`
# baseurl: ""

linkedin_url: TBD
twitter_username: TBD
github_username: netcom-deadlines
github_repo: netcom-deadlines.github.io

markdown: kramdown

